#!/bin/bash
#SBATCH -N 2
#SBATCH -p debug
#SBATCH -J FeO
#SBATCH -t 00:30:00


#OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread


#run the application:
srun -n 48 -c 2 /global/homes/s/stpi/Programs/elk-4.3.6/src/elk > log 

