#!/bin/bash -l

#SBATCH --job-name=lsda-test
#SBATCH --partition=med
#SBATCH --time=00:30:00
##SBATCH --nodes=1
##SBATCH --mem-per-cpu=2000
#SBATCH --ntasks=8

srun pw.x < pw.scf.in > pw.scf.out
srun projwfc.x < projwfc.dos.in > projwfc.dos.out
srun pw.x < pw.bands.in > pw.bands.out
srun projwfc.x < projwfc.fat.in > projwfc.fat.out
